name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all history for all branches and tags

    - name: Configure git
      run: |
        git config --global user.email "github@dontemails.net"
        git config --global user.name "github dontemails"

    - name: Sync with Upstream
      run: |
        git remote add upstream https://github.com/cmliu/edgetunnel.git
        git fetch upstream
        git checkout main
        git merge upstream/main
        git push origin main

