name: Sync Upstream

# This runs every day on 1801 UTC
on:
  schedule:
    - cron: '1 18 * * *'
  # Allows manual workflow run (must in default branch to work)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: envs
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: Andrey1994/sync-upstream-repo@0.0.2
        with: 
          upstream_repo: https://github.com/cmliu/edgetunnel.git # change this
          upstream_branch: main # change this
          downstream_branch: main # change this
          token: ${{ secrets.PAT_TOKEN }}